problem:
  nx: 100
  nt: 70
  epsilon: 0.01
  perturb: True

training:
  method: 'unsupervised'
  seed: 4
  niters: 0
  g_lr: 0.14148811247197426 #0.0014148811247197426
  d_lr: 0.093618095162488891 #0.00093618095162488891
  g_betas: [0.65372654, 0.55785936]
  d_betas: [0.68166835, 0.54224536]
  lr_schedule: True
  gamma: 0.99956297859137611
  noise: False
  step_size: 20
  obs_every: 1
  d1: 1
  d2: 1
  G_iters: 1
  D_iters: 1
  loss_fn: MSELoss
  wgan: False
  gp: 0.1
  conditional: False
  train_mse: False
  log: True
  plot: True
  plot_1d_curves: True
  save: True
  save_for_animation: False
  dirname: 'ACA_run'

generator:
  in_dim: 2
  out_dim: 1
  n_hidden_units: 30
  n_hidden_layers: 3
  activation: 'Tanh'
  residual: True
  regress: True
  pretrained: 'weights_allen_cahn.t.45'

discriminator:
  in_dim: 1
  out_dim: 1
  n_hidden_units: 50
  n_hidden_layers: 3
  activation: 'Tanh'
  residual: True
  regress: False
  spectral_norm: True
