problem:
  nx: 128
  nt: 128
  nx_p: 8000
  nt_p: 100
  epsilon: 0.001
  perturb: True

training:
  method: 'unsupervised'
  seed: 8
  niters: 20000
  g_lr: 0.013062663284027502
  d_lr: 0.018659887517260301
  g_betas: [0.59484321, 0.9425278]
  d_betas: [0.8017268, 0.37476167]
  lr_schedule: True
  gamma: 0.98905978163111818
  noise: False
  step_size: 13
  obs_every: 1
  d1: 1
  d2: 1
  G_iters: 1
  D_iters: 1
  loss_fn: MSELoss
  wgan: False
  gp: 0.1
  conditional: False
  train_mse: False
  log: True
  plot: True
  plot_1d_curves: True
  save: True
  save_for_animation: False
  dirname: 'ACA_run'

generator:
  in_dim: 2
  out_dim: 1
  n_hidden_units: 40
  n_hidden_layers: 3
  activation: 'Tanh'
  residual: True
  regress: True
  pretrained: False #'weights_allen_cahn.t.45'

discriminator:
  in_dim: 1
  out_dim: 1
  n_hidden_units: 50
  n_hidden_layers: 5
  activation: 'Tanh'
  residual: True
  regress: False
  spectral_norm: True
