problem:
  nx: 128
  nt: 128
  nu: 0.001
  perturb: True

training:
  method: 'unsupervised'
  seed: 0
  niters: 5000
  g_lr: 0.01419182684992092
  d_lr: 0.0037935152609284389
  g_betas: [0.18431666, 0.5183879]
  d_betas: [0.11145376, 0.17149793]
  lr_schedule: True
  gamma: 0.98400021927489023
  noise: False
  step_size: 10
  obs_every: 1
  d1: 1
  d2: 1
  G_iters: 1
  D_iters: 1
  loss_fn: MSELoss
  wgan: False
  gp: 0.1
  conditional: False
  train_mse: False
  log: True
  plot: True
  plot_1d_curves: True
  save: True
  save_for_animation: False
  dirname: 'BURV_run'

generator:
  in_dim: 2
  out_dim: 1
  n_hidden_units: 20
  n_hidden_layers: 3
  activation: 'Tanh'
  residual: True
  regress: True

discriminator:
  in_dim: 1
  out_dim: 1
  n_hidden_units: 20
  n_hidden_layers: 5
  activation: 'Tanh'
  residual: True
  regress: False
  spectral_norm: True
