problem:
  nx: 64
  nt: 64
  nx_p: 1000
  nt_p: 100
  nu: 0.001
  perturb: True

training:
  method: 'unsupervised'
  seed: 0
  niters: 3000 #5000
  g_lr: 0.012742949817104081 #0.01419182684992092
  d_lr: 0.0054264631919862987 #0.0037935152609284389
  g_betas: [0.18525066902093706, 0.5941217838175823] #[0.18431666, 0.5183879]
  d_betas: [0.09374523602184848, 0.18467156506542667] #[0.11145376, 0.17149793]
  lr_schedule: True
  gamma: 0.95484413617848396 #0.98400021927489023
  noise: False
  step_size: 20 #10
  obs_every: 1
  d1: 1
  d2: 1
  G_iters: 1
  D_iters: 1
  loss_fn: MSELoss
  wgan: False
  gp: 0.1
  conditional: False
  train_mse: False
  log: True
  plot: True
  plot_1d_curves: True
  save: True
  save_for_animation: False
  view: [35, -55]
  dirname: 'BURV_run'

generator:
  in_dim: 2
  out_dim: 1
  n_hidden_units: 50 #20
  n_hidden_layers: 3
  activation: 'Tanh'
  residual: True
  regress: True
  pretrained: False

discriminator:
  in_dim: 1
  out_dim: 1
  n_hidden_units: 20
  n_hidden_layers: 5
  activation: 'Tanh'
  residual: True
  regress: False
  spectral_norm: True
