problem:
  n: 100
  perturb: True
  z_0: 10
  Om_m_0: 0.15
  b: 5

training:
  method: 'unsupervised'
  seed: 6
  niters: 20000
  g_lr: 0.014757737962090883
  d_lr: 0.01193061114021309
  g_betas: [0.82571262, 0.12144184]
  d_betas: [0.75612857, 0.6972567]
  g_momentum: 0.94114125988931008
  d_momentum: 0.94114125988931008
  lr_schedule: True
  gamma: 0.94812914657589875
  noise: False
  step_size: 4
  obs_every: 1
  d1: 1
  d2: 1
  G_iters: 1
  D_iters: 1
  loss_fn: MSELoss
  wgan: False
  gp: 0.1
  conditional: False
  train_mse: True
  log: True
  plot: True
  plot_sep_curves: True
  save: True
  save_for_animation: False
  dirname: 'EINS_run'

generator:
  in_dim: 1
  out_dim: 5
  n_hidden_units: 30
  n_hidden_layers: 4
  activation: 'Tanh'
  residual: True
  regress: True

discriminator:
  in_dim: 5
  out_dim: 1
  n_hidden_units: 50
  n_hidden_layers: 2
  activation: 'Tanh'
  residual: True
  regress: False
  spectral_norm: True
