problem:
  n: 1000
  perturb: True
  z_0: 10
  Om_m_0: 0.15
  b: 5

training:
  method: 'unsupervised'
  seed: 7 #2
  niters: 30000
  g_lr: 0.00064044052778962379 #0.0013109727740075996
  d_lr: 0.0013847021063578639 #0.012703867271028131
  g_betas: [0.19316573, 0.67359447] #[0.32227323, 0.56971684]
  d_betas: [0.01741737, 0.8363446] #[0.70425699, 0.85826436]
  lr_schedule: True
  gamma: 0.99735444618782132 #0.97676331521658999
  noise: False
  step_size: 10 #19
  obs_every: 1
  d1: 1
  d2: 1
  G_iters: 1
  D_iters: 1
  loss_fn: MSELoss
  wgan: False
  gp: 0.1
  conditional: False
  train_mse: True
  log: True
  plot: True
  plot_sep_curves: True
  save: True
  save_for_animation: False
  dirname: 'EINS_run'

generator:
  in_dim: 1
  out_dim: 5
  n_hidden_units: 40 #50
  n_hidden_layers: 3 #2
  activation: 'Tanh'
  residual: True
  regress: True
  pretrained: False

discriminator:
  in_dim: 5
  out_dim: 1
  n_hidden_units: 40
  n_hidden_layers: 5 #2
  activation: 'Tanh'
  residual: True
  regress: False
  spectral_norm: True
