problem:
  n: 100
  perturb: True
  z_0: 10
  Om_m_0: 0.15
  b: 5

training:
  method: 'unsupervised'
  seed: 3
  niters: 200000
  g_lr: 0.016341959189231651
  d_lr: 0.014747434998428817
  g_betas: [0.13979895, 0.69997109]
  d_betas: [0.04317054, 0.52559446]
  g_momentum: 0.94114125988931008
  d_momentum: 0.94114125988931008
  lr_schedule: True
  gamma: 0.99130678856012755
  noise: False
  step_size: 13
  obs_every: 1
  d1: 1
  d2: 1
  G_iters: 1
  D_iters: 1
  loss_fn: MSELoss
  wgan: False
  gp: 0.1
  conditional: False
  train_mse: True
  log: True
  plot: True
  plot_sep_curves: True
  save: True
  save_for_animation: False
  dirname: 'EINS_run'

generator:
  in_dim: 1
  out_dim: 5
  n_hidden_units: 40
  n_hidden_layers: 3
  activation: 'Tanh'
  residual: True
  regress: True
  pretrained: False

discriminator:
  in_dim: 5
  out_dim: 1
  n_hidden_units: 20
  n_hidden_layers: 4
  activation: 'Tanh'
  residual: True
  regress: False
  spectral_norm: True
