problem:
  nx: 32
  nt: 32
  nx_p: 1000
  nt_p: 100
  perturb: True

training:
  method: 'unsupervised'
  seed: 9
  niters: 20000
  g_lr: 0.0097215459532903753
  d_lr: 0.0075983537564216254
  g_betas: [0.07161742, 0.22559733]
  d_betas: [0.73810679, 0.04723746]
  lr_schedule: True
  gamma: 0.98350906155731432
  noise: False
  step_size: 12
  obs_every: 1
  d1: 1
  d2: 1
  G_iters: 1
  D_iters: 1
  loss_fn: MSELoss
  wgan: False
  gp: 0.1
  conditional: False
  train_mse: False
  log: True
  plot: True
  plot_1d_curves: False
  save: True
  save_for_animation: False
  view: [35, -135]
  dirname: 'KUR_run'

generator:
  in_dim: 2
  out_dim: 1
  n_hidden_units: 40
  n_hidden_layers: 3
  activation: 'Tanh'
  residual: True
  regress: True
  pretrained: False

discriminator:
  in_dim: 1
  out_dim: 1
  n_hidden_units: 40
  n_hidden_layers: 2
  activation: 'Tanh'
  residual: True
  regress: False
  spectral_norm: True
