problem:
  n: 400
  sampling: 'fixed'
  t_max: 1
  x0: 0
  y0: [0., 0.07142857, 0.14285714, 0.21428571, 0.28571429, 0.35714286, 0.42857143, 0.5, 0.57142857, 0.64285714,
  0.71428571, 0.78571429, 0.85714286, 0.92857143, 1.]
  px0: 1
  py0: 0
  sigma: 0.1
  A: 0.1

training:
  method: 'unsupervised'
  seed: 2
  niters: 10000
  g_lr: 0.01152380515461927
  d_lr: 0.015452633350580029
  g_betas: [0.22881133152941593, 0.69984895289804]
  d_betas: [0.2758524687122676, 0.8291734341043192]
  lr_schedule: True
  gamma: 0.97782604967996123
  noise: True
  step_size: 11
  obs_every: 1
  d1: 1
  d2: 1
  G_iters: 1
  D_iters: 1
  loss_fn: MSELoss
  wgan: False
  gp: 0.1
  conditional: False
  train_mse: False
  log: True
  plot: True
  multihead: True
  plot_sep_curves: True
  save: True
  save_for_animation: False
  dirname: 'RAYS_run'

generator:
  in_dim: 1
  out_dim: 4
  n_hidden_units: 50
  n_hidden_layers: 4
  n_heads: 15
  n_head_units: 20
  activation: 'Tanh'
  residual: True
  regress: True
  pretrained: False

discriminator:
  in_dim: 4
  out_dim: 1
  n_hidden_units: 70
  n_hidden_layers: 4
  n_heads: 15
  activation: 'Tanh'
  residual: True
  regress: False
  spectral_norm: True
