problem:
  n: 400
  sampling: 'fixed'
  t_max: 1
  x0: 0
  y0: [0.00629415, 0.10790965, 0.16338743, 0.26396311, 0.31055611,
       0.42259726, 0.52199343, 0.57089518, 0.61662052, 0.67387798,
       0.99927758] #[0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
  px0: 1
  py0: 0
  sigma: 0.1
  A: 0.1

training:
  method: 'unsupervised'
  seed: 2
  niters: 10000
  g_lr: 0.012316433526697611
  d_lr: 0.0037547474147429367
  g_betas: [0.3321397465281695, 0.7814519177699136]
  d_betas: [0.08849280706193198, 0.9920535299846108]
  lr_schedule: True
  gamma: 0.98944605908056127
  noise: False
  step_size: 11
  obs_every: 1
  d1: 1
  d2: 1
  G_iters: 1
  D_iters: 1
  loss_fn: MSELoss
  wgan: False
  gp: 0.1
  conditional: False
  train_mse: False
  log: True
  plot: True
  multihead: True
  plot_sep_curves: True
  save: True
  save_G: False
  save_for_animation: False
  dirname: 'RAYS_run'

generator:
  in_dim: 1
  out_dim: 4
  n_hidden_units: 20
  n_hidden_layers: 5
  n_heads: 11
  n_head_units: 20
  activation: 'Tanh'
  residual: True
  regress: True
  pretrained: True

discriminator:
  in_dim: 4
  out_dim: 1
  n_hidden_units: 50
  n_hidden_layers: 2
  n_heads: 11
  activation: 'Tanh'
  residual: True
  regress: False
  spectral_norm: True
