name: denn
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch
  - tqdm
  - pandas
  - jupyterlab
  - matplotlib
  - scipy
  - pyyaml
  - boto3
  - plotly
  - plotly-orca
  - pip
  - pip:
    - torchvision
    - fenics
    - ray
    - ray[tune]
